# Generated by Django 3.2.5 on 2021-07-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, default='1', max_length=100),
            preserve_default=False,
        ),
    ]
