# Generated by Django 3.2.5 on 2021-07-22 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0006_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.profile'),
            preserve_default=False,
        ),
    ]
