# Generated by Django 3.2.5 on 2021-07-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0009_alter_profile_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='education',
            new_name='HTitle',
        ),
        migrations.AddField(
            model_name='profile',
            name='Highschool',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='STitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='School',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='UTitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='University',
            field=models.TextField(blank=True),
        ),
    ]
