# Generated by Django 3.2.5 on 2021-07-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0010_auto_20210722_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill1',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skill2',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skill3',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skill4',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skill5',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skill6',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
